version: "3"
services:

  mysql8:
    image: mysql:8.0.25
    command: --default_authentication_plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 设置初始化脚本
     - /Users/jcen/projects/mars/scripts/mysql/user.sql:/docker-entrypoint-initdb.d/user.sql
    ports:
      # 映射 13316端口
      - "33060:3306"
  redis:
    image: redis:7.0.0
    ports:
      - "16379:6379"
    environment:
      - REDIS_PASSWORD=123456
    volumes:
      - /Users/jcen/projects/mars/scripts/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
