// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/jwcen/mars/internal/apiserver/handler"
	"github.com/jwcen/mars/internal/apiserver/handler/jwt"
	"github.com/jwcen/mars/internal/apiserver/repository"
	"github.com/jwcen/mars/internal/apiserver/repository/cache"
	"github.com/jwcen/mars/internal/apiserver/repository/dao"
	"github.com/jwcen/mars/internal/apiserver/service"
	"github.com/jwcen/mars/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.InitMiddlewares(cmdable)
	db := ioc.InitDB()
	userDao := dao.NewUserDao(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewUserInfoRepository(userDao, userCache)
	userAndService := service.NewUserService(userRepository)
	jwtHandler := jwt.NewRedisJWTHandler(cmdable)
	userHandler := handler.NewUserHandler(userAndService, jwtHandler)
	engine := ioc.InitGinEngine(v, userHandler)
	return engine
}
