// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/jwcen/mars/internal/apiserver/handler"
	"github.com/jwcen/mars/internal/apiserver/handler/jwt"
	"github.com/jwcen/mars/internal/apiserver/repository"
	"github.com/jwcen/mars/internal/apiserver/repository/cache"
	"github.com/jwcen/mars/internal/apiserver/repository/dao"
	"github.com/jwcen/mars/internal/apiserver/service"
	"github.com/jwcen/mars/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := InitRedis()
	v := ioc.InitMiddlewares(cmdable)
	gormDB := InitTestDB()
	userDao := dao.NewUserDao(gormDB)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewUserInfoRepository(userDao, userCache)
	userAndService := service.NewUserService(userRepository)
	jwtHandler := jwt.NewRedisJWTHandler(cmdable)
	userHandler := handler.NewUserHandler(userAndService, jwtHandler)
	articleDao := dao.NewArticleDao(gormDB)
	articleRepository := repository.NewArticleRepository(articleDao)
	articleService := service.NewArticleService(articleRepository)
	articleHandler := handler.NewArticleHandler(articleService)
	engine := ioc.InitGinEngine(v, userHandler, articleHandler)
	return engine
}

func InitArticleHandler() *handler.ArticleHandler {
	gormDB := InitTestDB()
	articleDao := dao.NewArticleDao(gormDB)
	articleRepository := repository.NewArticleRepository(articleDao)
	articleService := service.NewArticleService(articleRepository)
	articleHandler := handler.NewArticleHandler(articleService)
	return articleHandler
}

// wire.go:

var thirdProvider = wire.NewSet(InitRedis, InitTestDB)

var userSvcProvider = wire.NewSet(dao.NewUserDao, cache.NewRedisUserCache, repository.NewUserInfoRepository, service.NewUserService)
